### ISSUE TITLE
Issue: Accuracy is lower when running on Collaboratory

### ISSUE THREAD

**Issue by thisisashwinraj** [zotroneneis/machine_learning_basics#16]
I tested the exact code on collaboratory and found the following:
Test accuracy with k = 1: 97.77777777777777
Test accuracy with k = 5: 97.55555555555556
![fshfshtshtshtshth](https://user-images.githubusercontent.com/62590141/77817663-bdfb9700-70f2-11ea-9230-cfea1d95df69.JPG)

**Comment by zotroneneis** [comment]
Could you specify what you mean with "collaboratory"?

**Comment by thisisashwinraj** [comment]
Google colab

**Comment by zotroneneis** [comment]
I'm not familiar with Google Colab. It might be due to the random seed. Did you fix the random seed in the beginning?
