### ISSUE TITLE
Question on basics and tools

### ISSUE THREAD

**Issue by deathblade287** [zotroneneis/machine_learning_basics#17]
Hi,
I am new to machine learning. I already know advanced python. Currently, I am using anaconda spyder for my codes, but I was hoping somebody could recommend an editor solely for machine learning and focused on "pandas" as well as "NumPy".

**Comment by TannerGilbert** [comment]
PyCharm is a great choice for data science and Python in general. For more information about data science specific features in PyCharm check out: https://www.jetbrains.com/pycharm/features/scientific_tools.html

**Comment by zotroneneis** [comment]
@greatestpythoncoder If you just want to play around with pandas and numpy you could try jupyter notebooks. For development I heard many good thinks about Visual Studio Code, but I don't use an IDE myself (I use nvim as an editor).
