### ISSUE TITLE
Random Forest Classifier

### ISSUE THREAD

**Issue by gopichandpuli9** [zotroneneis/machine_learning_basics#23]
Can I work on Random Forest Classifier issue?

**Comment by zotroneneis** [comment]
Sorry for not getting back to you @gopichandpuli9. I'm not sure what you're issue is about. Could you explain?

**Comment by markwong2019** [comment]
已收到，谢谢！

**Comment by zotroneneis** [comment]
> 已收到，谢谢！

No idea what that means :)
