### ISSUE TITLE
Question about a formulate

### ISSUE THREAD

**Issue by hope1337** [zotroneneis/machine_learning_basics#26]
![image](https://github.com/zotroneneis/machine_learning_basics/assets/120596914/2acd0d7a-f108-4710-8c42-f477069c30df)]

In the numerator, I think it should be $p(y|x, \theta)p(x|\theta)p(\theta)$, so why $p(x|\theta)$ disappear ?

**Comment by zotroneneis** [comment]
Thanks for your question! I would recommend looking at chapter 9.3 of the book "Mathematics for Machine Learning" (https://mml-book.github.io/book/mml-book.pdf). Specifically, chapter 9.3.3. should help :)

**Comment by hope1337** [comment]
> Thanks for your question! I would recommend looking at chapter 9.3 of the book "Mathematics for Machine Learning" (https://mml-book.github.io/book/mml-book.pdf). Specifically, chapter 9.3.3. should help :)

According to the mentioned book : 
![image](https://github.com/zotroneneis/machine_learning_basics/assets/120596914/13d7c733-691c-4d01-a03a-c58edaadd18d)

That is $p(y|x)$ instead of $p(x, y)$ if in numerator does not contain $p(x|\theta)$.

**Comment by zotroneneis** [comment]
You're completely right! I corrected it. Thank you!
