### ISSUE TITLE
not a issue but a request!

### ISSUE THREAD

**Issue by nagexiucai** [zotroneneis/machine_learning_basics#8]
Thanks for these clear tutorials for basics of machine learning.

I have read through with great honor and translated into Chinese, and errata #7 as well.

Now i wish to contribute them as a Chinese version, just put this [link](https://github.com/nagexiucai/MLA/blob/master/机器学习基础（Anna-Lena%20Popkes）中文版.md) into README.md can come true.

**Comment by zotroneneis** [comment]
Thanks for your contribution! I have received several request of this kind already. I have put a lot of effort into making sure that the explanations are correct. Therefore, I won't add any translations that I cannot review myself.
